language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: Rjr9SnIPr47jbqO1Lv9gdt8AbzT2L69EibEGGINwpRN+Wc8ylmZE/YmHji5DtQAkblX8kBPMeAbDRf3qKl6Gu0R/2kgM+YTE5tRYRb6lZ9Xrwdcez6tVej/y7x+tg+aT6wzQ2ejXDtx5uxenb7cGxGrL+dG70N/4CzkU2Coxw7w82JWhtvmhwsUWQOT9YpeV4CVKEiJcOXzcVU4ifrksCMMAFDL+4PCDv+KNnPS7/F9vZl2cXzek5HXrQhhhrpGjxHVqtsD+or2JBqA+WxYK/CVm8/EfrYHTezduzVTUg0Ru7tbhivf3ZJ37Wz6hhwe9rXBcX6FgDGkM570ZiCyQNFHPX+Squ3YWEFiPlTEe1VEyz8yoIBRSC04otzBeKlkg16c+WwWydSERpghWo9PDwaHsS0JpbzE6sy6KFJrWFF/ZourncjRgUd2hFE866chX44RqNH/xQ5iidLRJKqzOFSyVLQCQYsvPjparZelkOFfj8MPh0Zj9l/CnSqeB5gUtvFfPKe5y0GWWUHnR0whJTLe7RiCq2LAfWpK+5IP9k+PnzYd72C1owTyWVG0cXnEyW3zoyU2hfV8FVqgyGO6aI/OB9VvGpvwc5NE8WqXstrQDuMQdk715NDidg9UDOH2YCx5oHk7njz4mKHWhD9QA3euO5OI9JK8ABZOaUHyR4sE=
  app: campusmapa-02
  on:
    repo: uva-cs3240-s21/project-a-02
    branch: main
