# Generated by Django 3.1.5 on 2021-03-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_mnemonic', models.CharField(max_length=200)),
                ('course_number', models.IntegerField()),
                ('class_section', models.IntegerField()),
                ('class_type', models.CharField(max_length=200)),
                ('class_units', models.IntegerField()),
                ('class_instructor', models.CharField(max_length=200)),
                ('class_days', models.DateTimeField()),
                ('class_room', models.CharField(max_length=200)),
                ('class_title', models.CharField(max_length=200)),
                ('class_topic', models.CharField(max_length=200)),
                ('class_status', models.CharField(max_length=200)),
                ('class_enrollment', models.IntegerField()),
                ('class_enrollment_limit', models.IntegerField()),
                ('class_waitlist', models.IntegerField()),
                ('class_description', models.CharField(max_length=200)),
            ],
        ),
    ]
