# Generated by Django 3.1.5 on 2021-04-13 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='user',
            field=models.ManyToManyField(related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_units',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField(help_text='In the form MM/DD/YY hh:mm')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('attendees', models.ManyToManyField(default=None, related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
