# Generated by Django 3.1.5 on 2021-04-05 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_auto_20210309_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='user',
            field=models.ManyToManyField(related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_units',
            field=models.FloatField(),
        ),
    ]
