# Generated by Django 3.1.6 on 2021-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_eventmodel_numberofattendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
