# Generated by Django 3.1.5 on 2021-04-01 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_auto_20210328_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='user',
            field=models.ManyToManyField(related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
