# Generated by Django 3.1.5 on 2021-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_coursesmodel_schedulemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('classCode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CoursesModel',
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='map.CourseModel'),
        ),
    ]
