# Generated by Django 3.1.7 on 2021-05-03 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210503_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
