# Generated by Django 3.1.7 on 2021-04-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_eventmodel_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
