# Generated by Django 3.1.7 on 2021-04-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210412_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(help_text='In the form MM/DD/YY hh:mm'),
        ),
    ]
