# Generated by Django 3.1.7 on 2021-03-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_classmodel_class_combined_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='class_combined_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.classmodel'),
        ),
    ]
