# Generated by Django 3.1.7 on 2021-03-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210309_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='class_combined_with',
        ),
    ]
