# Generated by Django 3.1.5 on 2021-03-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
