# Generated by Django 3.1.7 on 2021-03-28 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0010_course_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='CourseModel',
        ),
        migrations.RenameModel(
            old_name='schedule',
            new_name='ScheduleModel',
        ),
    ]
